[config]
exclude-merge-commits=true
check-summary-length=true
summary-length=70

[matchers]
conventional="(?:feat|test|fix|docs|refactor|perf|chore)(\\(.*?\\))?: .*?\n(?:\n?(?:\\* |  ).*?\n)*"
release="release [0-9]+.[0-9]+.[0-9]+"

[examples]
a_simple_commit="""
[feat|test|fix|docs|refactor|perf|chore](module)?: A commit message
"""
an_extended_commit="""
[feat|test|fix|docs|refactor|perf|chore](module)? : A commit message

* first line
* second line
* and so on...
"""
